site_name: Yizhou Shan's Home Page
site_author: 'Yizhou Shan'
site_url: 'http://lastweek.io'

nav:
- Home: 'index.md'
- Notes:
   - 'Modern Virtualization':                               'notes/virt.md'
   - 'Practical Cache Coherence':                           'notes/cache_coherence.md'
   - 'Dynamic Linking':                                     'notes/dynamic_linking.md'
   - 'Data Center Networking':                              'notes/dcn.md'
   - 'Switch Buffering and Packet Scheduling':              'notes/packet-sched.md'
   - 'SysML':                                               'notes/sysml.md'
   - 'Architecture':                                        'notes/arch.md'
   - 'Cryptography':                                        'notes/cryptography.md'
   - 'Cryptocurrency':                                      'notes/cryptocurrency.md'
   - 'Hardware Design Languages':                           'notes/hardware_pl.md'
   - 'Performance-Shadows':                                 'notes/paper_perf_shadows.md'
   - 'Essential':                                           'misc/essential.md'
   #- 'Benchmarks':                                          'notes/benchmark.md'
   - 'Cheatsheet':                                          'misc/cheatsheet.md'
   - 'On Read Once and Compiler Optimization':    'blog/20200404-on-read-once.md'
- Code:
   - 'Index':                       'notes/source_code/summary.md'
   - Linux:
     - 'Linux Index':                                         'notes/linux/index.md'
     - 'Linux fork/switch_to':                                'notes/linux/fork.md'
     - 'Linux RCU':                                           'notes/linux/linux-rcu.md'
     - 'Linux Boot Sequence':                                 'notes/linux/linux-boot.md'
     - 'Linux Trace and Profile':                             'notes/trace.md'
     - 'Linux Reverse Mapping':                               'notes/rmap.md'
     - 'Linux Userfaultfd':                                   'notes/userfaultfd.md'
     - 'Linux Cgroup and Swap':                               'notes/cgroup-swap.md'
     - 'Linux x86 Ring Switch':                               'notes/xperf.md'
     - 'Linux FPU':                                           'notes/linux/linux-x86-fpu.md'
     - 'Linux io_uring':                                      'notes/linux/linux-iouring.md'
     - 'Linux Resource':                                      'notes/linux/linux-resource.md'
     - 'Linux Special Files':                                 'notes/proc.md'
     - 'Linux KVM':                                           'notes/kvm-basic.md'
   - 'Guideline & Advice':          'notes/program_advice.md'
   - 'Firmware & Bootloader':       'notes/source_code/firmware-softwares.md'
   - 'Operating System':            'notes/source_code/os.md'
   - 'Compilers':                   'notes/source_code/compilers.md'
   - 'Unix Tools':                  'notes/source_code/unix-tools.md'
   - 'Virtualization':              'notes/source_code/virt.md'
   - 'DPDK and RDMA':               'notes/source_code/rdma.md'
   - 'Graphics':                    'notes/source_code/20200501-on-graphic-softwares.md'
   - 'GPU':                         'notes/source_code/gpu.md'
   - 'FPGA':                        'notes/source_code/fpga.md'
   - 'RISC-V':                      'notes/source_code/risc-v.md'
   - 'Dot-Configs':                 'notes/source_code/dotconfigs.md'
   - 'Misc':                        'notes/source_code/misc.md'
- FPGA:
   - 'Bitstream Explained':                  'fpga/bitstream.md'
   - 'Papers':                               'notes/paper_fpga.md'
   - 'Languages':                            'fpga/language.md'
   - 'Vivado Notes':                         'fpga/vivado.md'
   - 'Setup and Hold Time':                  'fpga/setup_hold.md'
   - 'Partial Reconfiguration':              'fpga/pr.md'
   #- 'Efficient AXI-MM':                     'fpga/hls_axi.md'
# - HowTo:
#    - "How to add an IOMMU device in QEMU?":   'howto/qemu-iommu.md'
- LegoOS:
   - 'Log':
#           - 'TODO':                    'lego/log/TODO.md'
           - 'MISC':                    'lego/log/misc.md'
           - 'Test Script':             'lego/log/test-note.md'
#           - 'Sep 2018':                'lego/log/log-09-2018.md'
#           - 'Aug 2018':                'lego/log/log-08-2018.md'
#           - 'April 2018':              'lego/log/log-04-2018.md'
#           - 'March 2018':              'lego/log/log-03-2018.md'
#           - 'Feb 2018':                'lego/log/log-02-2018.md'
   - 'Kernel':
        - 'GRUB2 and Boot' : 'lego/kernel/boot.md'
        - 'Kconfig': 'lego/kernel/kconfig.md'
        - 'Debug': 'lego/kernel/debug.md'
        - 'GRUB': 'lego/kernel/grub.md'
        - 'Profile': 'lego/kernel/profile.md'
        - 'Profile strace': 'lego/kernel/profile_strace.md'
        - 'Profile heatmap': 'lego/kernel/profile_heatmap.md'
        - 'Profile points': 'lego/kernel/profile_points.md'
        - 'Trampoline': 'lego/kernel/trampoline.md'
        - 'Disable pgfault': 'lego/kernel/pagefault_disable.md'
        - 'Stop machine': 'lego/kernel/stop_machine.md'
        - 'Program Loader': 'lego/kernel/loader.md'
        - 'vDSO': 'lego/kernel/vDSO.md'
        - 'Virtual File System': 'lego/kernel/vfs.md'
        - 'Process Virtual Memory': 'lego/kernel/vm.md'
        - 'x86 FPU': 'lego/kernel/fpu.md'
        - 'IRQ': 'lego/kernel/irq.md'
        - 'Network Thpool': 'lego/kernel/net_thpool.md'
   - Syscall:
           - 'Facts':         'lego/syscall/facts.md'
           - 'strace': 'lego/kernel/profile_strace.md'
           - 'compat':        'lego/syscall/compat.md'
           - 'msync()':       'lego/syscall/msync.md'
           - 'mremap()':      'lego/syscall/mremap.md'
           - 'fork()':        'lego/syscall/fork.md'
           - 'getrusage()':   'lego/syscall/getrusage.md'
           - 'wait4 and exit()': 'lego/syscall/wait_and_exit.md'
   - Pcache:
           - 'Config': 'lego/pcache/config.md'
           - 'Sweep': 'lego/pcache/sweep.md'
           - 'TLB Coherence': 'lego/pcache/tlb.md'
           - 'PageTable Lock': 'lego/pcache/pgtable-lock.md'
           - 'Victim Cache': 'lego/pcache/victim.md'
           - 'Virtual Cache': 'lego/pcache/virtual_cache.md'
           - 'Reverse Mapping': 'lego/pcache/rmap.md'
           - 'Evict and Refcount': 'lego/pcache/evict_and_ref.md'
           - 'SMP Design': 'lego/pcache/smp_design.md'
           - 'Replication': 'lego/pcache/replication.md'
   - Driver:
           - 'PCI': 'lego/driver/pci.md'
           - 'Infiniband': 'lego/driver/ib.md'
   - Paper:
           - 'NMP': 'lego/paper/nmp.md'
           - 'Processor OOM': 'lego/paper/processor_oom.md'
           - 'Gen-Z': 'lego/paper/genz.md'
           - 'Replication': 'lego/paper/replication.md'
           - 'Related': 'lego/paper/related.md'

#- Financial:
    #    - "Stock": 'financial/stock.md'
    # - "Behavior Economics": 'financial/economics_behavior.md'
    # - "Economics": 'financial/economics.md'

markdown_extensions:
  - attr_list
  - admonition
  - tables
  - smarty
  - footnotes
  - codehilite:
      linenums: true
      guess_lang: true
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.progressbar

plugins:
  - search
  - git-revision-date-localized

#name: 'material'
#name: 'rtd-dropdown'
#name: 'gitbook'
#name: 'readthedocs'
theme:
  name: 'material'
  font:
    text: Courier Prime Bold
    code: Courier Prime Bold
  icon:
    #logo: material/cloud
    repo: fontawesome/brands/gitlab
  features:
    - instant
    - tabs
    - navigation.tabs
    - navigation.top
#  palette:
    #scheme: slate
    #primary: black
    #accent: deep purple

google_analytics:
  - 'UA-143772066-1'
  - 'auto'

#extra_css:
#  - stylesheets/extra.css

# Options
extra:
  logo: "images/logo.svg"
    # social:
    # - type: 'github'
    #   link: 'https://github.com/lastweek'
    # - type: 'twitter'
    #   link: 'https://twitter.com/Yizhou_Shan'
    # - type: 'linkedin'
    #   link: 'https://www.linkedin.com/in/lastweek/'
  disqus: 'lastweek-io'

repo_url: https://github.com/lastweek/lastweek.github.io
